package com.scott.fu.entity.mes;

import java.math.BigDecimal;
import java.util.Date;

public class ProductionOrderStep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Lot_Num_MES
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String lotNumMes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Lot_Num_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String lotNumSap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Step
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Lot_Type_MES
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String lotTypeMes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Lot_Type_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String lotTypeSap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Part_Num
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String partNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.WorkCenter
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String workcenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.EnterStepTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private Date entersteptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Resource
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Machine_Num_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String machineNumSap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Input_UNIT
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private BigDecimal inputUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Output_UNIT
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private BigDecimal outputUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Input_QPanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private BigDecimal inputQpanel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Output_Qpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private BigDecimal outputQpanel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Input_Fpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private BigDecimal inputFpanel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.Output_Fpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private BigDecimal outputFpanel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.ModifiedBy
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private String modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.UpdateTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.TrackInTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private Date trackintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES.T_ProductionOrderStep.TrackOutTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    private Date trackouttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Lot_Num_MES
     *
     * @return the value of MES.T_ProductionOrderStep.Lot_Num_MES
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getLotNumMes() {
        return lotNumMes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Lot_Num_MES
     *
     * @param lotNumMes the value for MES.T_ProductionOrderStep.Lot_Num_MES
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setLotNumMes(String lotNumMes) {
        this.lotNumMes = lotNumMes == null ? null : lotNumMes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Lot_Num_SAP
     *
     * @return the value of MES.T_ProductionOrderStep.Lot_Num_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getLotNumSap() {
        return lotNumSap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Lot_Num_SAP
     *
     * @param lotNumSap the value for MES.T_ProductionOrderStep.Lot_Num_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setLotNumSap(String lotNumSap) {
        this.lotNumSap = lotNumSap == null ? null : lotNumSap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Step
     *
     * @return the value of MES.T_ProductionOrderStep.Step
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Step
     *
     * @param step the value for MES.T_ProductionOrderStep.Step
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Lot_Type_MES
     *
     * @return the value of MES.T_ProductionOrderStep.Lot_Type_MES
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getLotTypeMes() {
        return lotTypeMes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Lot_Type_MES
     *
     * @param lotTypeMes the value for MES.T_ProductionOrderStep.Lot_Type_MES
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setLotTypeMes(String lotTypeMes) {
        this.lotTypeMes = lotTypeMes == null ? null : lotTypeMes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Lot_Type_SAP
     *
     * @return the value of MES.T_ProductionOrderStep.Lot_Type_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getLotTypeSap() {
        return lotTypeSap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Lot_Type_SAP
     *
     * @param lotTypeSap the value for MES.T_ProductionOrderStep.Lot_Type_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setLotTypeSap(String lotTypeSap) {
        this.lotTypeSap = lotTypeSap == null ? null : lotTypeSap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Part_Num
     *
     * @return the value of MES.T_ProductionOrderStep.Part_Num
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getPartNum() {
        return partNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Part_Num
     *
     * @param partNum the value for MES.T_ProductionOrderStep.Part_Num
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setPartNum(String partNum) {
        this.partNum = partNum == null ? null : partNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.WorkCenter
     *
     * @return the value of MES.T_ProductionOrderStep.WorkCenter
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getWorkcenter() {
        return workcenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.WorkCenter
     *
     * @param workcenter the value for MES.T_ProductionOrderStep.WorkCenter
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setWorkcenter(String workcenter) {
        this.workcenter = workcenter == null ? null : workcenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.EnterStepTime
     *
     * @return the value of MES.T_ProductionOrderStep.EnterStepTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Date getEntersteptime() {
        return entersteptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.EnterStepTime
     *
     * @param entersteptime the value for MES.T_ProductionOrderStep.EnterStepTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setEntersteptime(Date entersteptime) {
        this.entersteptime = entersteptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Resource
     *
     * @return the value of MES.T_ProductionOrderStep.Resource
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Resource
     *
     * @param resource the value for MES.T_ProductionOrderStep.Resource
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Machine_Num_SAP
     *
     * @return the value of MES.T_ProductionOrderStep.Machine_Num_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getMachineNumSap() {
        return machineNumSap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Machine_Num_SAP
     *
     * @param machineNumSap the value for MES.T_ProductionOrderStep.Machine_Num_SAP
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setMachineNumSap(String machineNumSap) {
        this.machineNumSap = machineNumSap == null ? null : machineNumSap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Input_UNIT
     *
     * @return the value of MES.T_ProductionOrderStep.Input_UNIT
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public BigDecimal getInputUnit() {
        return inputUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Input_UNIT
     *
     * @param inputUnit the value for MES.T_ProductionOrderStep.Input_UNIT
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setInputUnit(BigDecimal inputUnit) {
        this.inputUnit = inputUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Output_UNIT
     *
     * @return the value of MES.T_ProductionOrderStep.Output_UNIT
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public BigDecimal getOutputUnit() {
        return outputUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Output_UNIT
     *
     * @param outputUnit the value for MES.T_ProductionOrderStep.Output_UNIT
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setOutputUnit(BigDecimal outputUnit) {
        this.outputUnit = outputUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Input_QPanel
     *
     * @return the value of MES.T_ProductionOrderStep.Input_QPanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public BigDecimal getInputQpanel() {
        return inputQpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Input_QPanel
     *
     * @param inputQpanel the value for MES.T_ProductionOrderStep.Input_QPanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setInputQpanel(BigDecimal inputQpanel) {
        this.inputQpanel = inputQpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Output_Qpanel
     *
     * @return the value of MES.T_ProductionOrderStep.Output_Qpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public BigDecimal getOutputQpanel() {
        return outputQpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Output_Qpanel
     *
     * @param outputQpanel the value for MES.T_ProductionOrderStep.Output_Qpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setOutputQpanel(BigDecimal outputQpanel) {
        this.outputQpanel = outputQpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Input_Fpanel
     *
     * @return the value of MES.T_ProductionOrderStep.Input_Fpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public BigDecimal getInputFpanel() {
        return inputFpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Input_Fpanel
     *
     * @param inputFpanel the value for MES.T_ProductionOrderStep.Input_Fpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setInputFpanel(BigDecimal inputFpanel) {
        this.inputFpanel = inputFpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.Output_Fpanel
     *
     * @return the value of MES.T_ProductionOrderStep.Output_Fpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public BigDecimal getOutputFpanel() {
        return outputFpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.Output_Fpanel
     *
     * @param outputFpanel the value for MES.T_ProductionOrderStep.Output_Fpanel
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setOutputFpanel(BigDecimal outputFpanel) {
        this.outputFpanel = outputFpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.ModifiedBy
     *
     * @return the value of MES.T_ProductionOrderStep.ModifiedBy
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.ModifiedBy
     *
     * @param modifiedby the value for MES.T_ProductionOrderStep.ModifiedBy
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby == null ? null : modifiedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.UpdateTime
     *
     * @return the value of MES.T_ProductionOrderStep.UpdateTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.UpdateTime
     *
     * @param updatetime the value for MES.T_ProductionOrderStep.UpdateTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.TrackInTime
     *
     * @return the value of MES.T_ProductionOrderStep.TrackInTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Date getTrackintime() {
        return trackintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.TrackInTime
     *
     * @param trackintime the value for MES.T_ProductionOrderStep.TrackInTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setTrackintime(Date trackintime) {
        this.trackintime = trackintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES.T_ProductionOrderStep.TrackOutTime
     *
     * @return the value of MES.T_ProductionOrderStep.TrackOutTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Date getTrackouttime() {
        return trackouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES.T_ProductionOrderStep.TrackOutTime
     *
     * @param trackouttime the value for MES.T_ProductionOrderStep.TrackOutTime
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setTrackouttime(Date trackouttime) {
        this.trackouttime = trackouttime;
    }
}