package com.scott.fu.entity.mes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductionOrderStepExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public ProductionOrderStepExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLotNumMesIsNull() {
            addCriterion("Lot_Num_MES is null");
            return (Criteria) this;
        }

        public Criteria andLotNumMesIsNotNull() {
            addCriterion("Lot_Num_MES is not null");
            return (Criteria) this;
        }

        public Criteria andLotNumMesEqualTo(String value) {
            addCriterion("Lot_Num_MES =", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotEqualTo(String value) {
            addCriterion("Lot_Num_MES <>", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesGreaterThan(String value) {
            addCriterion("Lot_Num_MES >", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Num_MES >=", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesLessThan(String value) {
            addCriterion("Lot_Num_MES <", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesLessThanOrEqualTo(String value) {
            addCriterion("Lot_Num_MES <=", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesLike(String value) {
            addCriterion("Lot_Num_MES like", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotLike(String value) {
            addCriterion("Lot_Num_MES not like", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesIn(List<String> values) {
            addCriterion("Lot_Num_MES in", values, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotIn(List<String> values) {
            addCriterion("Lot_Num_MES not in", values, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesBetween(String value1, String value2) {
            addCriterion("Lot_Num_MES between", value1, value2, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotBetween(String value1, String value2) {
            addCriterion("Lot_Num_MES not between", value1, value2, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumSapIsNull() {
            addCriterion("Lot_Num_SAP is null");
            return (Criteria) this;
        }

        public Criteria andLotNumSapIsNotNull() {
            addCriterion("Lot_Num_SAP is not null");
            return (Criteria) this;
        }

        public Criteria andLotNumSapEqualTo(String value) {
            addCriterion("Lot_Num_SAP =", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotEqualTo(String value) {
            addCriterion("Lot_Num_SAP <>", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapGreaterThan(String value) {
            addCriterion("Lot_Num_SAP >", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Num_SAP >=", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapLessThan(String value) {
            addCriterion("Lot_Num_SAP <", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapLessThanOrEqualTo(String value) {
            addCriterion("Lot_Num_SAP <=", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapLike(String value) {
            addCriterion("Lot_Num_SAP like", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotLike(String value) {
            addCriterion("Lot_Num_SAP not like", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapIn(List<String> values) {
            addCriterion("Lot_Num_SAP in", values, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotIn(List<String> values) {
            addCriterion("Lot_Num_SAP not in", values, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapBetween(String value1, String value2) {
            addCriterion("Lot_Num_SAP between", value1, value2, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotBetween(String value1, String value2) {
            addCriterion("Lot_Num_SAP not between", value1, value2, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andStepIsNull() {
            addCriterion("Step is null");
            return (Criteria) this;
        }

        public Criteria andStepIsNotNull() {
            addCriterion("Step is not null");
            return (Criteria) this;
        }

        public Criteria andStepEqualTo(String value) {
            addCriterion("Step =", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotEqualTo(String value) {
            addCriterion("Step <>", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThan(String value) {
            addCriterion("Step >", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepGreaterThanOrEqualTo(String value) {
            addCriterion("Step >=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThan(String value) {
            addCriterion("Step <", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLessThanOrEqualTo(String value) {
            addCriterion("Step <=", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepLike(String value) {
            addCriterion("Step like", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotLike(String value) {
            addCriterion("Step not like", value, "step");
            return (Criteria) this;
        }

        public Criteria andStepIn(List<String> values) {
            addCriterion("Step in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotIn(List<String> values) {
            addCriterion("Step not in", values, "step");
            return (Criteria) this;
        }

        public Criteria andStepBetween(String value1, String value2) {
            addCriterion("Step between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andStepNotBetween(String value1, String value2) {
            addCriterion("Step not between", value1, value2, "step");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesIsNull() {
            addCriterion("Lot_Type_MES is null");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesIsNotNull() {
            addCriterion("Lot_Type_MES is not null");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesEqualTo(String value) {
            addCriterion("Lot_Type_MES =", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotEqualTo(String value) {
            addCriterion("Lot_Type_MES <>", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesGreaterThan(String value) {
            addCriterion("Lot_Type_MES >", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Type_MES >=", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesLessThan(String value) {
            addCriterion("Lot_Type_MES <", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesLessThanOrEqualTo(String value) {
            addCriterion("Lot_Type_MES <=", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesLike(String value) {
            addCriterion("Lot_Type_MES like", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotLike(String value) {
            addCriterion("Lot_Type_MES not like", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesIn(List<String> values) {
            addCriterion("Lot_Type_MES in", values, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotIn(List<String> values) {
            addCriterion("Lot_Type_MES not in", values, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesBetween(String value1, String value2) {
            addCriterion("Lot_Type_MES between", value1, value2, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotBetween(String value1, String value2) {
            addCriterion("Lot_Type_MES not between", value1, value2, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapIsNull() {
            addCriterion("Lot_Type_SAP is null");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapIsNotNull() {
            addCriterion("Lot_Type_SAP is not null");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapEqualTo(String value) {
            addCriterion("Lot_Type_SAP =", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotEqualTo(String value) {
            addCriterion("Lot_Type_SAP <>", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapGreaterThan(String value) {
            addCriterion("Lot_Type_SAP >", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Type_SAP >=", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapLessThan(String value) {
            addCriterion("Lot_Type_SAP <", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapLessThanOrEqualTo(String value) {
            addCriterion("Lot_Type_SAP <=", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapLike(String value) {
            addCriterion("Lot_Type_SAP like", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotLike(String value) {
            addCriterion("Lot_Type_SAP not like", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapIn(List<String> values) {
            addCriterion("Lot_Type_SAP in", values, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotIn(List<String> values) {
            addCriterion("Lot_Type_SAP not in", values, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapBetween(String value1, String value2) {
            addCriterion("Lot_Type_SAP between", value1, value2, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotBetween(String value1, String value2) {
            addCriterion("Lot_Type_SAP not between", value1, value2, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andPartNumIsNull() {
            addCriterion("Part_Num is null");
            return (Criteria) this;
        }

        public Criteria andPartNumIsNotNull() {
            addCriterion("Part_Num is not null");
            return (Criteria) this;
        }

        public Criteria andPartNumEqualTo(String value) {
            addCriterion("Part_Num =", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotEqualTo(String value) {
            addCriterion("Part_Num <>", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumGreaterThan(String value) {
            addCriterion("Part_Num >", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumGreaterThanOrEqualTo(String value) {
            addCriterion("Part_Num >=", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumLessThan(String value) {
            addCriterion("Part_Num <", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumLessThanOrEqualTo(String value) {
            addCriterion("Part_Num <=", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumLike(String value) {
            addCriterion("Part_Num like", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotLike(String value) {
            addCriterion("Part_Num not like", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumIn(List<String> values) {
            addCriterion("Part_Num in", values, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotIn(List<String> values) {
            addCriterion("Part_Num not in", values, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumBetween(String value1, String value2) {
            addCriterion("Part_Num between", value1, value2, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotBetween(String value1, String value2) {
            addCriterion("Part_Num not between", value1, value2, "partNum");
            return (Criteria) this;
        }

        public Criteria andWorkcenterIsNull() {
            addCriterion("WorkCenter is null");
            return (Criteria) this;
        }

        public Criteria andWorkcenterIsNotNull() {
            addCriterion("WorkCenter is not null");
            return (Criteria) this;
        }

        public Criteria andWorkcenterEqualTo(String value) {
            addCriterion("WorkCenter =", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterNotEqualTo(String value) {
            addCriterion("WorkCenter <>", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterGreaterThan(String value) {
            addCriterion("WorkCenter >", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterGreaterThanOrEqualTo(String value) {
            addCriterion("WorkCenter >=", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterLessThan(String value) {
            addCriterion("WorkCenter <", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterLessThanOrEqualTo(String value) {
            addCriterion("WorkCenter <=", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterLike(String value) {
            addCriterion("WorkCenter like", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterNotLike(String value) {
            addCriterion("WorkCenter not like", value, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterIn(List<String> values) {
            addCriterion("WorkCenter in", values, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterNotIn(List<String> values) {
            addCriterion("WorkCenter not in", values, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterBetween(String value1, String value2) {
            addCriterion("WorkCenter between", value1, value2, "workcenter");
            return (Criteria) this;
        }

        public Criteria andWorkcenterNotBetween(String value1, String value2) {
            addCriterion("WorkCenter not between", value1, value2, "workcenter");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeIsNull() {
            addCriterion("EnterStepTime is null");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeIsNotNull() {
            addCriterion("EnterStepTime is not null");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeEqualTo(Date value) {
            addCriterion("EnterStepTime =", value, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeNotEqualTo(Date value) {
            addCriterion("EnterStepTime <>", value, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeGreaterThan(Date value) {
            addCriterion("EnterStepTime >", value, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("EnterStepTime >=", value, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeLessThan(Date value) {
            addCriterion("EnterStepTime <", value, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeLessThanOrEqualTo(Date value) {
            addCriterion("EnterStepTime <=", value, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeIn(List<Date> values) {
            addCriterion("EnterStepTime in", values, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeNotIn(List<Date> values) {
            addCriterion("EnterStepTime not in", values, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeBetween(Date value1, Date value2) {
            addCriterion("EnterStepTime between", value1, value2, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andEntersteptimeNotBetween(Date value1, Date value2) {
            addCriterion("EnterStepTime not between", value1, value2, "entersteptime");
            return (Criteria) this;
        }

        public Criteria andResourceIsNull() {
            addCriterion("Resource is null");
            return (Criteria) this;
        }

        public Criteria andResourceIsNotNull() {
            addCriterion("Resource is not null");
            return (Criteria) this;
        }

        public Criteria andResourceEqualTo(String value) {
            addCriterion("Resource =", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotEqualTo(String value) {
            addCriterion("Resource <>", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceGreaterThan(String value) {
            addCriterion("Resource >", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceGreaterThanOrEqualTo(String value) {
            addCriterion("Resource >=", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLessThan(String value) {
            addCriterion("Resource <", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLessThanOrEqualTo(String value) {
            addCriterion("Resource <=", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLike(String value) {
            addCriterion("Resource like", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotLike(String value) {
            addCriterion("Resource not like", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceIn(List<String> values) {
            addCriterion("Resource in", values, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotIn(List<String> values) {
            addCriterion("Resource not in", values, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceBetween(String value1, String value2) {
            addCriterion("Resource between", value1, value2, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotBetween(String value1, String value2) {
            addCriterion("Resource not between", value1, value2, "resource");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapIsNull() {
            addCriterion("Machine_Num_SAP is null");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapIsNotNull() {
            addCriterion("Machine_Num_SAP is not null");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapEqualTo(String value) {
            addCriterion("Machine_Num_SAP =", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapNotEqualTo(String value) {
            addCriterion("Machine_Num_SAP <>", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapGreaterThan(String value) {
            addCriterion("Machine_Num_SAP >", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapGreaterThanOrEqualTo(String value) {
            addCriterion("Machine_Num_SAP >=", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapLessThan(String value) {
            addCriterion("Machine_Num_SAP <", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapLessThanOrEqualTo(String value) {
            addCriterion("Machine_Num_SAP <=", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapLike(String value) {
            addCriterion("Machine_Num_SAP like", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapNotLike(String value) {
            addCriterion("Machine_Num_SAP not like", value, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapIn(List<String> values) {
            addCriterion("Machine_Num_SAP in", values, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapNotIn(List<String> values) {
            addCriterion("Machine_Num_SAP not in", values, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapBetween(String value1, String value2) {
            addCriterion("Machine_Num_SAP between", value1, value2, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andMachineNumSapNotBetween(String value1, String value2) {
            addCriterion("Machine_Num_SAP not between", value1, value2, "machineNumSap");
            return (Criteria) this;
        }

        public Criteria andInputUnitIsNull() {
            addCriterion("Input_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andInputUnitIsNotNull() {
            addCriterion("Input_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andInputUnitEqualTo(BigDecimal value) {
            addCriterion("Input_UNIT =", value, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitNotEqualTo(BigDecimal value) {
            addCriterion("Input_UNIT <>", value, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitGreaterThan(BigDecimal value) {
            addCriterion("Input_UNIT >", value, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Input_UNIT >=", value, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitLessThan(BigDecimal value) {
            addCriterion("Input_UNIT <", value, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Input_UNIT <=", value, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitIn(List<BigDecimal> values) {
            addCriterion("Input_UNIT in", values, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitNotIn(List<BigDecimal> values) {
            addCriterion("Input_UNIT not in", values, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Input_UNIT between", value1, value2, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andInputUnitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Input_UNIT not between", value1, value2, "inputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitIsNull() {
            addCriterion("Output_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andOutputUnitIsNotNull() {
            addCriterion("Output_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andOutputUnitEqualTo(BigDecimal value) {
            addCriterion("Output_UNIT =", value, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitNotEqualTo(BigDecimal value) {
            addCriterion("Output_UNIT <>", value, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitGreaterThan(BigDecimal value) {
            addCriterion("Output_UNIT >", value, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Output_UNIT >=", value, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitLessThan(BigDecimal value) {
            addCriterion("Output_UNIT <", value, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Output_UNIT <=", value, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitIn(List<BigDecimal> values) {
            addCriterion("Output_UNIT in", values, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitNotIn(List<BigDecimal> values) {
            addCriterion("Output_UNIT not in", values, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Output_UNIT between", value1, value2, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andOutputUnitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Output_UNIT not between", value1, value2, "outputUnit");
            return (Criteria) this;
        }

        public Criteria andInputQpanelIsNull() {
            addCriterion("Input_QPanel is null");
            return (Criteria) this;
        }

        public Criteria andInputQpanelIsNotNull() {
            addCriterion("Input_QPanel is not null");
            return (Criteria) this;
        }

        public Criteria andInputQpanelEqualTo(BigDecimal value) {
            addCriterion("Input_QPanel =", value, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelNotEqualTo(BigDecimal value) {
            addCriterion("Input_QPanel <>", value, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelGreaterThan(BigDecimal value) {
            addCriterion("Input_QPanel >", value, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Input_QPanel >=", value, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelLessThan(BigDecimal value) {
            addCriterion("Input_QPanel <", value, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Input_QPanel <=", value, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelIn(List<BigDecimal> values) {
            addCriterion("Input_QPanel in", values, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelNotIn(List<BigDecimal> values) {
            addCriterion("Input_QPanel not in", values, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Input_QPanel between", value1, value2, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputQpanelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Input_QPanel not between", value1, value2, "inputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelIsNull() {
            addCriterion("Output_Qpanel is null");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelIsNotNull() {
            addCriterion("Output_Qpanel is not null");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelEqualTo(BigDecimal value) {
            addCriterion("Output_Qpanel =", value, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelNotEqualTo(BigDecimal value) {
            addCriterion("Output_Qpanel <>", value, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelGreaterThan(BigDecimal value) {
            addCriterion("Output_Qpanel >", value, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Output_Qpanel >=", value, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelLessThan(BigDecimal value) {
            addCriterion("Output_Qpanel <", value, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Output_Qpanel <=", value, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelIn(List<BigDecimal> values) {
            addCriterion("Output_Qpanel in", values, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelNotIn(List<BigDecimal> values) {
            addCriterion("Output_Qpanel not in", values, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Output_Qpanel between", value1, value2, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andOutputQpanelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Output_Qpanel not between", value1, value2, "outputQpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelIsNull() {
            addCriterion("Input_Fpanel is null");
            return (Criteria) this;
        }

        public Criteria andInputFpanelIsNotNull() {
            addCriterion("Input_Fpanel is not null");
            return (Criteria) this;
        }

        public Criteria andInputFpanelEqualTo(BigDecimal value) {
            addCriterion("Input_Fpanel =", value, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelNotEqualTo(BigDecimal value) {
            addCriterion("Input_Fpanel <>", value, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelGreaterThan(BigDecimal value) {
            addCriterion("Input_Fpanel >", value, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Input_Fpanel >=", value, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelLessThan(BigDecimal value) {
            addCriterion("Input_Fpanel <", value, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Input_Fpanel <=", value, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelIn(List<BigDecimal> values) {
            addCriterion("Input_Fpanel in", values, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelNotIn(List<BigDecimal> values) {
            addCriterion("Input_Fpanel not in", values, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Input_Fpanel between", value1, value2, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andInputFpanelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Input_Fpanel not between", value1, value2, "inputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelIsNull() {
            addCriterion("Output_Fpanel is null");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelIsNotNull() {
            addCriterion("Output_Fpanel is not null");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelEqualTo(BigDecimal value) {
            addCriterion("Output_Fpanel =", value, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelNotEqualTo(BigDecimal value) {
            addCriterion("Output_Fpanel <>", value, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelGreaterThan(BigDecimal value) {
            addCriterion("Output_Fpanel >", value, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Output_Fpanel >=", value, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelLessThan(BigDecimal value) {
            addCriterion("Output_Fpanel <", value, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Output_Fpanel <=", value, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelIn(List<BigDecimal> values) {
            addCriterion("Output_Fpanel in", values, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelNotIn(List<BigDecimal> values) {
            addCriterion("Output_Fpanel not in", values, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Output_Fpanel between", value1, value2, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andOutputFpanelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Output_Fpanel not between", value1, value2, "outputFpanel");
            return (Criteria) this;
        }

        public Criteria andModifiedbyIsNull() {
            addCriterion("ModifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andModifiedbyIsNotNull() {
            addCriterion("ModifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedbyEqualTo(String value) {
            addCriterion("ModifiedBy =", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyNotEqualTo(String value) {
            addCriterion("ModifiedBy <>", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyGreaterThan(String value) {
            addCriterion("ModifiedBy >", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyGreaterThanOrEqualTo(String value) {
            addCriterion("ModifiedBy >=", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyLessThan(String value) {
            addCriterion("ModifiedBy <", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyLessThanOrEqualTo(String value) {
            addCriterion("ModifiedBy <=", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyLike(String value) {
            addCriterion("ModifiedBy like", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyNotLike(String value) {
            addCriterion("ModifiedBy not like", value, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyIn(List<String> values) {
            addCriterion("ModifiedBy in", values, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyNotIn(List<String> values) {
            addCriterion("ModifiedBy not in", values, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyBetween(String value1, String value2) {
            addCriterion("ModifiedBy between", value1, value2, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andModifiedbyNotBetween(String value1, String value2) {
            addCriterion("ModifiedBy not between", value1, value2, "modifiedby");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UpdateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UpdateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UpdateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UpdateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UpdateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UpdateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UpdateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UpdateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UpdateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeIsNull() {
            addCriterion("TrackInTime is null");
            return (Criteria) this;
        }

        public Criteria andTrackintimeIsNotNull() {
            addCriterion("TrackInTime is not null");
            return (Criteria) this;
        }

        public Criteria andTrackintimeEqualTo(Date value) {
            addCriterion("TrackInTime =", value, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeNotEqualTo(Date value) {
            addCriterion("TrackInTime <>", value, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeGreaterThan(Date value) {
            addCriterion("TrackInTime >", value, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TrackInTime >=", value, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeLessThan(Date value) {
            addCriterion("TrackInTime <", value, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeLessThanOrEqualTo(Date value) {
            addCriterion("TrackInTime <=", value, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeIn(List<Date> values) {
            addCriterion("TrackInTime in", values, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeNotIn(List<Date> values) {
            addCriterion("TrackInTime not in", values, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeBetween(Date value1, Date value2) {
            addCriterion("TrackInTime between", value1, value2, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackintimeNotBetween(Date value1, Date value2) {
            addCriterion("TrackInTime not between", value1, value2, "trackintime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeIsNull() {
            addCriterion("TrackOutTime is null");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeIsNotNull() {
            addCriterion("TrackOutTime is not null");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeEqualTo(Date value) {
            addCriterion("TrackOutTime =", value, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeNotEqualTo(Date value) {
            addCriterion("TrackOutTime <>", value, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeGreaterThan(Date value) {
            addCriterion("TrackOutTime >", value, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TrackOutTime >=", value, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeLessThan(Date value) {
            addCriterion("TrackOutTime <", value, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeLessThanOrEqualTo(Date value) {
            addCriterion("TrackOutTime <=", value, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeIn(List<Date> values) {
            addCriterion("TrackOutTime in", values, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeNotIn(List<Date> values) {
            addCriterion("TrackOutTime not in", values, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeBetween(Date value1, Date value2) {
            addCriterion("TrackOutTime between", value1, value2, "trackouttime");
            return (Criteria) this;
        }

        public Criteria andTrackouttimeNotBetween(Date value1, Date value2) {
            addCriterion("TrackOutTime not between", value1, value2, "trackouttime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 28 09:59:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}