package com.scott.fu.entity.mes;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductionOrderHeadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public ProductionOrderHeadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLotNumMesIsNull() {
            addCriterion("Lot_Num_MES is null");
            return (Criteria) this;
        }

        public Criteria andLotNumMesIsNotNull() {
            addCriterion("Lot_Num_MES is not null");
            return (Criteria) this;
        }

        public Criteria andLotNumMesEqualTo(String value) {
            addCriterion("Lot_Num_MES =", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotEqualTo(String value) {
            addCriterion("Lot_Num_MES <>", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesGreaterThan(String value) {
            addCriterion("Lot_Num_MES >", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Num_MES >=", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesLessThan(String value) {
            addCriterion("Lot_Num_MES <", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesLessThanOrEqualTo(String value) {
            addCriterion("Lot_Num_MES <=", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesLike(String value) {
            addCriterion("Lot_Num_MES like", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotLike(String value) {
            addCriterion("Lot_Num_MES not like", value, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesIn(List<String> values) {
            addCriterion("Lot_Num_MES in", values, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotIn(List<String> values) {
            addCriterion("Lot_Num_MES not in", values, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesBetween(String value1, String value2) {
            addCriterion("Lot_Num_MES between", value1, value2, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumMesNotBetween(String value1, String value2) {
            addCriterion("Lot_Num_MES not between", value1, value2, "lotNumMes");
            return (Criteria) this;
        }

        public Criteria andLotNumSapIsNull() {
            addCriterion("Lot_Num_SAP is null");
            return (Criteria) this;
        }

        public Criteria andLotNumSapIsNotNull() {
            addCriterion("Lot_Num_SAP is not null");
            return (Criteria) this;
        }

        public Criteria andLotNumSapEqualTo(String value) {
            addCriterion("Lot_Num_SAP =", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotEqualTo(String value) {
            addCriterion("Lot_Num_SAP <>", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapGreaterThan(String value) {
            addCriterion("Lot_Num_SAP >", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Num_SAP >=", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapLessThan(String value) {
            addCriterion("Lot_Num_SAP <", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapLessThanOrEqualTo(String value) {
            addCriterion("Lot_Num_SAP <=", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapLike(String value) {
            addCriterion("Lot_Num_SAP like", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotLike(String value) {
            addCriterion("Lot_Num_SAP not like", value, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapIn(List<String> values) {
            addCriterion("Lot_Num_SAP in", values, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotIn(List<String> values) {
            addCriterion("Lot_Num_SAP not in", values, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapBetween(String value1, String value2) {
            addCriterion("Lot_Num_SAP between", value1, value2, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotNumSapNotBetween(String value1, String value2) {
            addCriterion("Lot_Num_SAP not between", value1, value2, "lotNumSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesIsNull() {
            addCriterion("Lot_Type_MES is null");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesIsNotNull() {
            addCriterion("Lot_Type_MES is not null");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesEqualTo(String value) {
            addCriterion("Lot_Type_MES =", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotEqualTo(String value) {
            addCriterion("Lot_Type_MES <>", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesGreaterThan(String value) {
            addCriterion("Lot_Type_MES >", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Type_MES >=", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesLessThan(String value) {
            addCriterion("Lot_Type_MES <", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesLessThanOrEqualTo(String value) {
            addCriterion("Lot_Type_MES <=", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesLike(String value) {
            addCriterion("Lot_Type_MES like", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotLike(String value) {
            addCriterion("Lot_Type_MES not like", value, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesIn(List<String> values) {
            addCriterion("Lot_Type_MES in", values, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotIn(List<String> values) {
            addCriterion("Lot_Type_MES not in", values, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesBetween(String value1, String value2) {
            addCriterion("Lot_Type_MES between", value1, value2, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeMesNotBetween(String value1, String value2) {
            addCriterion("Lot_Type_MES not between", value1, value2, "lotTypeMes");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapIsNull() {
            addCriterion("Lot_Type_SAP is null");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapIsNotNull() {
            addCriterion("Lot_Type_SAP is not null");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapEqualTo(String value) {
            addCriterion("Lot_Type_SAP =", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotEqualTo(String value) {
            addCriterion("Lot_Type_SAP <>", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapGreaterThan(String value) {
            addCriterion("Lot_Type_SAP >", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapGreaterThanOrEqualTo(String value) {
            addCriterion("Lot_Type_SAP >=", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapLessThan(String value) {
            addCriterion("Lot_Type_SAP <", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapLessThanOrEqualTo(String value) {
            addCriterion("Lot_Type_SAP <=", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapLike(String value) {
            addCriterion("Lot_Type_SAP like", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotLike(String value) {
            addCriterion("Lot_Type_SAP not like", value, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapIn(List<String> values) {
            addCriterion("Lot_Type_SAP in", values, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotIn(List<String> values) {
            addCriterion("Lot_Type_SAP not in", values, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapBetween(String value1, String value2) {
            addCriterion("Lot_Type_SAP between", value1, value2, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andLotTypeSapNotBetween(String value1, String value2) {
            addCriterion("Lot_Type_SAP not between", value1, value2, "lotTypeSap");
            return (Criteria) this;
        }

        public Criteria andPartNumIsNull() {
            addCriterion("Part_Num is null");
            return (Criteria) this;
        }

        public Criteria andPartNumIsNotNull() {
            addCriterion("Part_Num is not null");
            return (Criteria) this;
        }

        public Criteria andPartNumEqualTo(String value) {
            addCriterion("Part_Num =", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotEqualTo(String value) {
            addCriterion("Part_Num <>", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumGreaterThan(String value) {
            addCriterion("Part_Num >", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumGreaterThanOrEqualTo(String value) {
            addCriterion("Part_Num >=", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumLessThan(String value) {
            addCriterion("Part_Num <", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumLessThanOrEqualTo(String value) {
            addCriterion("Part_Num <=", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumLike(String value) {
            addCriterion("Part_Num like", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotLike(String value) {
            addCriterion("Part_Num not like", value, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumIn(List<String> values) {
            addCriterion("Part_Num in", values, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotIn(List<String> values) {
            addCriterion("Part_Num not in", values, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumBetween(String value1, String value2) {
            addCriterion("Part_Num between", value1, value2, "partNum");
            return (Criteria) this;
        }

        public Criteria andPartNumNotBetween(String value1, String value2) {
            addCriterion("Part_Num not between", value1, value2, "partNum");
            return (Criteria) this;
        }

        public Criteria andProjectIsNull() {
            addCriterion("Project is null");
            return (Criteria) this;
        }

        public Criteria andProjectIsNotNull() {
            addCriterion("Project is not null");
            return (Criteria) this;
        }

        public Criteria andProjectEqualTo(String value) {
            addCriterion("Project =", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotEqualTo(String value) {
            addCriterion("Project <>", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThan(String value) {
            addCriterion("Project >", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThanOrEqualTo(String value) {
            addCriterion("Project >=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThan(String value) {
            addCriterion("Project <", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThanOrEqualTo(String value) {
            addCriterion("Project <=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLike(String value) {
            addCriterion("Project like", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotLike(String value) {
            addCriterion("Project not like", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectIn(List<String> values) {
            addCriterion("Project in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotIn(List<String> values) {
            addCriterion("Project not in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectBetween(String value1, String value2) {
            addCriterion("Project between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotBetween(String value1, String value2) {
            addCriterion("Project not between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andPlantIsNull() {
            addCriterion("Plant is null");
            return (Criteria) this;
        }

        public Criteria andPlantIsNotNull() {
            addCriterion("Plant is not null");
            return (Criteria) this;
        }

        public Criteria andPlantEqualTo(String value) {
            addCriterion("Plant =", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotEqualTo(String value) {
            addCriterion("Plant <>", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThan(String value) {
            addCriterion("Plant >", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThanOrEqualTo(String value) {
            addCriterion("Plant >=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThan(String value) {
            addCriterion("Plant <", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThanOrEqualTo(String value) {
            addCriterion("Plant <=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLike(String value) {
            addCriterion("Plant like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotLike(String value) {
            addCriterion("Plant not like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantIn(List<String> values) {
            addCriterion("Plant in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotIn(List<String> values) {
            addCriterion("Plant not in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantBetween(String value1, String value2) {
            addCriterion("Plant between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotBetween(String value1, String value2) {
            addCriterion("Plant not between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeIsNull() {
            addCriterion("Lot_UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeIsNotNull() {
            addCriterion("Lot_UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeEqualTo(Date value) {
            addCriterion("Lot_UpdateTime =", value, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeNotEqualTo(Date value) {
            addCriterion("Lot_UpdateTime <>", value, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeGreaterThan(Date value) {
            addCriterion("Lot_UpdateTime >", value, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Lot_UpdateTime >=", value, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeLessThan(Date value) {
            addCriterion("Lot_UpdateTime <", value, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("Lot_UpdateTime <=", value, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeIn(List<Date> values) {
            addCriterion("Lot_UpdateTime in", values, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeNotIn(List<Date> values) {
            addCriterion("Lot_UpdateTime not in", values, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("Lot_UpdateTime between", value1, value2, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andLotUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("Lot_UpdateTime not between", value1, value2, "lotUpdatetime");
            return (Criteria) this;
        }

        public Criteria andSystemstatusIsNull() {
            addCriterion("SystemStatus is null");
            return (Criteria) this;
        }

        public Criteria andSystemstatusIsNotNull() {
            addCriterion("SystemStatus is not null");
            return (Criteria) this;
        }

        public Criteria andSystemstatusEqualTo(String value) {
            addCriterion("SystemStatus =", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusNotEqualTo(String value) {
            addCriterion("SystemStatus <>", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusGreaterThan(String value) {
            addCriterion("SystemStatus >", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusGreaterThanOrEqualTo(String value) {
            addCriterion("SystemStatus >=", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusLessThan(String value) {
            addCriterion("SystemStatus <", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusLessThanOrEqualTo(String value) {
            addCriterion("SystemStatus <=", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusLike(String value) {
            addCriterion("SystemStatus like", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusNotLike(String value) {
            addCriterion("SystemStatus not like", value, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusIn(List<String> values) {
            addCriterion("SystemStatus in", values, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusNotIn(List<String> values) {
            addCriterion("SystemStatus not in", values, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusBetween(String value1, String value2) {
            addCriterion("SystemStatus between", value1, value2, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andSystemstatusNotBetween(String value1, String value2) {
            addCriterion("SystemStatus not between", value1, value2, "systemstatus");
            return (Criteria) this;
        }

        public Criteria andUniversalstateIsNull() {
            addCriterion("UniversalState is null");
            return (Criteria) this;
        }

        public Criteria andUniversalstateIsNotNull() {
            addCriterion("UniversalState is not null");
            return (Criteria) this;
        }

        public Criteria andUniversalstateEqualTo(String value) {
            addCriterion("UniversalState =", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateNotEqualTo(String value) {
            addCriterion("UniversalState <>", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateGreaterThan(String value) {
            addCriterion("UniversalState >", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateGreaterThanOrEqualTo(String value) {
            addCriterion("UniversalState >=", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateLessThan(String value) {
            addCriterion("UniversalState <", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateLessThanOrEqualTo(String value) {
            addCriterion("UniversalState <=", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateLike(String value) {
            addCriterion("UniversalState like", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateNotLike(String value) {
            addCriterion("UniversalState not like", value, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateIn(List<String> values) {
            addCriterion("UniversalState in", values, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateNotIn(List<String> values) {
            addCriterion("UniversalState not in", values, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateBetween(String value1, String value2) {
            addCriterion("UniversalState between", value1, value2, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUniversalstateNotBetween(String value1, String value2) {
            addCriterion("UniversalState not between", value1, value2, "universalstate");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("Update_Time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("Update_Time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("Update_Time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("Update_Time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("Update_Time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Update_Time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("Update_Time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Update_Time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("Update_Time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("Update_Time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("Update_Time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Update_Time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusIsNull() {
            addCriterion("Update_Status is null");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusIsNotNull() {
            addCriterion("Update_Status is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusEqualTo(String value) {
            addCriterion("Update_Status =", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotEqualTo(String value) {
            addCriterion("Update_Status <>", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusGreaterThan(String value) {
            addCriterion("Update_Status >", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Update_Status >=", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusLessThan(String value) {
            addCriterion("Update_Status <", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusLessThanOrEqualTo(String value) {
            addCriterion("Update_Status <=", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusLike(String value) {
            addCriterion("Update_Status like", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotLike(String value) {
            addCriterion("Update_Status not like", value, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusIn(List<String> values) {
            addCriterion("Update_Status in", values, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotIn(List<String> values) {
            addCriterion("Update_Status not in", values, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusBetween(String value1, String value2) {
            addCriterion("Update_Status between", value1, value2, "updateStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateStatusNotBetween(String value1, String value2) {
            addCriterion("Update_Status not between", value1, value2, "updateStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 28 09:59:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}