package com.scott.fu.dao.mes;

import com.scott.fu.entity.mes.ProductionOrderStepScrap;
import com.scott.fu.entity.mes.ProductionOrderStepScrapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionOrderStepScrapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStepScrap
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int countByExample(ProductionOrderStepScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStepScrap
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int deleteByExample(ProductionOrderStepScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStepScrap
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int insert(ProductionOrderStepScrap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStepScrap
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int insertSelective(ProductionOrderStepScrap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStepScrap
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    List<ProductionOrderStepScrap> selectByExample(ProductionOrderStepScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStepScrap
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductionOrderStepScrap record, @Param("example") ProductionOrderStepScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStepScrap
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int updateByExample(@Param("record") ProductionOrderStepScrap record, @Param("example") ProductionOrderStepScrapExample example);
}