package com.scott.fu.dao.mes;

import com.scott.fu.entity.mes.ProductionOrderHead;
import com.scott.fu.entity.mes.ProductionOrderHeadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionOrderHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int countByExample(ProductionOrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int deleteByExample(ProductionOrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int insert(ProductionOrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int insertSelective(ProductionOrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    List<ProductionOrderHead> selectByExample(ProductionOrderHeadExample example);

    List<ProductionOrderHead> selectOrderHeadFetchSteps(String lotName);

    List<ProductionOrderHead> selectOrderHeadFetchStepsForHalfDayMetro();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductionOrderHead record, @Param("example") ProductionOrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderHead
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int updateByExample(@Param("record") ProductionOrderHead record, @Param("example") ProductionOrderHeadExample example);
}