package com.scott.fu.dao.mes;

import com.scott.fu.entity.mes.ProductionOrderStep;
import com.scott.fu.entity.mes.ProductionOrderStepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionOrderStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int countByExample(ProductionOrderStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int deleteByExample(ProductionOrderStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int insert(ProductionOrderStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int insertSelective(ProductionOrderStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    List<ProductionOrderStep> selectByExample(ProductionOrderStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProductionOrderStep record, @Param("example") ProductionOrderStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES.T_ProductionOrderStep
     *
     * @mbggenerated Mon Dec 28 09:59:22 CST 2015
     */
    int updateByExample(@Param("record") ProductionOrderStep record, @Param("example") ProductionOrderStepExample example);
}